### ISSUE TITLE
all endpoints redirect to login

### ISSUE THREAD

**Issue by Fedeya** [Propolisa/htb-api-docs#1]
when i use a endpoints, redirect to login, i need to use api token in query parameter or header?

![image](https://i.imgur.com/IgdcC5R.png)

**Comment by Propolisa** [comment]
Hey Fedeya!

Good question. Unlike the v3 api, v4 uses `Authorization: Bearer [API_TOKEN]` header mechanism. You can see an example login flow in my NodeJS-based HTB Discord bot code here: [Propolisa/Seven/modules/api.js](https://github.com/Propolisa/Seven/blob/94b12be2d30bd5ef1a278f25d95630f89810770b/modules/api.js#L31)
Note how the token is saved and [used in htbApiGet() method](https://github.com/Propolisa/Seven/blob/94b12be2d30bd5ef1a278f25d95630f89810770b/modules/api.js#L64). 

Feel free to dig around and copy from the Seven code as I'm updating that API interface more frequently than this repo.
Let me know if you still have any questions! 🙂

**Comment by Fedeya** [comment]
Thanks Propolisa!

**Comment by psyray** [comment]
Hi,
Sorry for posting in a closed ticket but it's the same problem.
With your API, imported in postman, all user Profile endoint works.
But the others redirect on the login page (or display **Unauthenicated** if **Accept header** is set to **application/json**).

Here's a request for User that works
![image](https://user-images.githubusercontent.com/1230954/107794997-6db41480-6d58-11eb-9714-af03a0d6bc09.png)

Here's  request for Machines that redirect to login
![image](https://user-images.githubusercontent.com/1230954/107795291-c388bc80-6d58-11eb-8fd9-6c55bfda78f9.png)

Same headers, different response.
If I force the **Accept header** to application/json, no redirect but a **Unauthenticated** response
![image](https://user-images.githubusercontent.com/1230954/107795767-5de90000-6d59-11eb-9995-aa9e57273674.png)

Do you know where this authentication problem comes from ?
There is only one API token, and it's always passed in the request header.

Thanks
